AUDIO_ROOT := $(srctree)/techpack/audio

############ UAPI ############
UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)

############ COMMON ############
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

ifeq ($(CONFIG_ARCH_ATOLL), y)
	UAPI_DIR :=     uapi
	UAPI_INC :=     -I$(AUDIO_ROOT)/4.0/include/$(UAPI_DIR)
	COMMON_DIR :=   include
	COMMON_INC :=   -I$(AUDIO_ROOT)/4.0/$(COMMON_DIR)
endif

############ TAS2562 ############

# for TAS2562 Codec
ifeq ($(CONFIG_SND_SOC_TAS2562), y)
	EXTRA_CFLAGS += -DCONFIG_TAS2562_REGMAP -DCONFIG_TAS2562_CODEC
	TAS2562_OBJS := tas2562-codec.o tas2562-regmap.o
endif

#for TAS25XX Algorithm Interface
ifeq ($(CONFIG_TAS25XX_ALGO), y)
	EXTRA_CFLAGS += -DCONFIG_TAS25XX_ALGO
	TAS2562_OBJS += tas25xx-algo.o tas25xx-calib.o
endif

LINUX_INC +=	-Iinclude/linux

INCS +=		$(COMMON_INC) \
		$(UAPI_INC)

EXTRA_CFLAGS += $(INCS)


CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
		-DANI_LITTLE_BIT_ENDIAN \
		-DDOT11F_LITTLE_ENDIAN_HOST \
		-DANI_COMPILER_TYPE_GCC \
		-DANI_OS_TYPE_ANDROID=6 \
		-DPTT_SOCK_SVC_ENABLE \
		-Wall\
		-Werror\
		-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

# Currently, for versions of gcc which support it, the kernel Makefile
# is disabling the maybe-uninitialized warning.  Re-enable it for the
# AUDIO driver.  Note that we must use EXTRA_CFLAGS here so that it
# will override the kernel settings.
ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif
#EXTRA_CFLAGS += -Wmissing-prototypes

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_TAS2562) += tas2562_dlkm.o
tas2562_dlkm-y := $(TAS2562_OBJS)
